# Generated by Django 4.1.2 on 2022-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile_photo', models.CharField(max_length=512)),
                ('is_started', models.BooleanField()),
            ],
        ),
    ]
