# Generated by Django 4.1.2 on 2022-11-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='connections',
            new_name='connection',
        ),
    ]
