# Generated by Django 4.1.2 on 2022-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_connections_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='password',
            field=models.CharField(default='123', max_length=16),
        ),
        migrations.AlterField(
            model_name='connection',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
