# Generated by Django 4.1.2 on 2022-11-22 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Account',
        ),
    ]
