# Generated by Django 4.1.2 on 2022-11-22 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_userid_account_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=255)),
                ('timeStamp', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
