# Generated by Django 4.1.2 on 2022-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_connected_userconnection_userconnected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
